add credits to nvchad and add my reddit profile in the credits
ThemerCorp/themer.lua pull request #57
Opened 2022-02-16 07:50 UTC by TarunDaCoder

2022-02-16 12:19 UTC, NarutoXY requested changes

2022-02-16 12:19 UTC, NarutoXY commented on README.md
> +- NvChad, for the new base16 palette
We should do something like
```suggestion
  - Creators of all the themes, in themer.
  - NvChad community (some themes are ported from nvchad's base16 plugin)
  - All those who helped in porting the themes to themer
```

2022-02-17 04:21 UTC, TarunDaCoder commented on README.md
> +- NvChad, for the new base16 palette
Yeah

2022-02-18 12:57 UTC, NarutoXY approved these changes

2022-02-18 12:57 UTC, merged